export const LOGGER_MESSAGES = {
  EMAIL_SENT: 'OTP email sent',
  USER_CREATED: 'User created successfully',
  PASSWORD_UPDATED: 'Password updated successfully',
  OTP_REQUEST_LIMIT: 'OTP request limit reached',
  LOGIN_ATTEMPT: 'Login attempt',
  USER_CREATION_FAILED: 'User creation failed',
  ADMIN_CREATED: 'Admin account created',
  ADMIN_LOGIN_SUCCESS: 'Admin logged in',
  ADMIN_BLOCK_USER: 'Blocked a user',
  ADMIN_UNBLOCK_USER: 'Unblocked a user',
  ADMIN_LOGOUT: 'Admin logged out',
    ADMIN_SIGNUP_FAILED: 'Admin signup failed',
  ADMIN_LOGIN_FAILED: 'Admin login failed',
  CREATE: 'Task created',
  UPDATE: 'Task updated',
  DELETE: 'Task deleted',
  PROJECT_CREATED: 'Project created',
 PROJECT_CREATION_FAILED: 'Project creation failed',
 MEMBERS_ASSIGNED: 'Members assigned to project',
 ASSIGN_MEMBERS_FAILED: 'Failed to assign members to project',
TASKS_ASSIGNED: 'Tasks assigned to project',
  ASSIGN_TASKS_FAILED: 'Failed to assign tasks to project',
  FETCH_PROJECTS_FAILED: 'Failed to fetch projects',
  COMMENT_CREATED: 'Comment created',
  COMMENT_CREATION_FAILED: 'Comment creation failed',
  COMMENT_UPDATED: 'Comment updated',
  COMMENT_DELETED: 'Comment deleted',
  COMMENT_FETCHED: 'Comments fetched for task',
  COMMENT_FETCH_FAILED: 'Failed to fetch comments for task',
  USER_FETCHED: 'User fetched successfully',
  ADD_COMMENT_FAILED: 'Failed to add comment',
  FETCH_COMMENTS_FAILED: 'Failed to fetch comments',
  UPDATE_COMMENT_FAILED: 'Failed to update comment',
  DELETE_COMMENT_FAILED: 'Failed to delete comment',
  TASK_FETCHED: 'Task fetched successfully',
  TASK_FETCH_FAILED: 'Failed to fetch task',
  AUDIT_LOG_CREATED: 'Audit log created',
  AUDIT_LOG_FAILED: 'Failed to create audit log',
  ADD_COMMENT:'add comment',
  UPLOAD_ATTACHMENT:'upload attachment',
};