export const USER_MESSAGES = {
  USER_EXISTS: 'User already exists',
  USER_NOT_FOUND: 'User not found',
  EMAIL_ALREADY_VERIFIED: 'Email already verified',
  EMAIL_ALREADY_IN_USE: 'Email already in use',
  INVALID_CREDENTIALS: 'Invalid email or password',
  EMAIL_NOT_VERIFIED: 'Email not verified',
  ACCOUNT_INACTIVE: 'Account is inactive',
  OTP_LIMIT_REACHED: 'OTP request limit reached. Try later.',
  OTP_EXPIRED: 'OTP expired or not found',
  TOO_MANY_ATTEMPTS: 'Too many invalid attempts. OTP expired.',
  INVALID_OTP: (attempt: number) => `Invalid OTP. Attempt ${attempt}/5`,
  OTP_SENT: 'OTP sent to your email',
  OTP_RESENT: 'OTP resent to your email',
  EMAIL_VERIFIED: 'Email verified successfully',
  LOGIN_SUCCESS: 'Login successful',
  PASSWORD_RESET_SUCCESS: 'Password reset successful',
  PASSWORD_CHANGED_SUCCESS: 'Password changed successfully',
  PROFILE_UPDATED_SUCCESS: 'Profile updated successfully',
  LOGOUT_SUCCESS: 'Logged out successfully',
  UNAUTHORIZED: 'Unauthorized access',
  INVALID_TOKEN: 'Invalid token',
  ROLE_MISMATCH: 'Role mismatch',
  MISSING_USER_OR_OTP: 'Missing user ID or OTP',
  MISSING_USER_ID: 'Missing user ID',

  //admin messages
  ADMIN_EXISTS: 'Admin already exists',
  ADMIN_NOT_FOUND: 'Admin not found',
  ADMIN_CREATED: 'Admin created successfully',
  ADMIN_UPDATED: 'Admin updated successfully',  
  ADMIN_DELETED: 'Admin deleted successfully',
  ADMIN_LOGIN_SUCCESS: 'Admin login successful',
  ADMIN_LOGOUT_SUCCESS: 'Admin logged out successfully',
  USER_BLOCKED: 'User blocked successfully',
  USER_UNBLOCKED: 'User unblocked successfully',
  USER_SEARCH_EMPTY: 'No users found for the search query',
  USER_SEARCH_ERROR: 'Error occurred while searching users',
  USER_PROFILE_FETCHED: 'User profile fetched successfully',
  USER_PROFILE_UPDATE_ERROR: 'Error occurred while updating user profile',
  USER_PROFILE_FETCH_ERROR: 'Error occurred while fetching user profile',
  USER_PROFILE_UPDATE_SUCCESS: 'User profile updated successfully',
  USER_PROFILE_DELETE_SUCCESS: 'User profile deleted successfully',
  USER_PROFILE_DELETE_ERROR: 'Error occurred while deleting user profile',
  USER_FETCH_SUCCESS: 'User details fetched successfully',
  ADMIN_ONLY_ASSIGN:'only admin can assign',
  USER_SEARCH_SUCCESS: 'User search completed successfully',

  //task messages
  TASK_CREATED: 'Task created successfully',
  TASK_UPDATED: 'Task updated successfully',
  TASK_DELETED: 'Task deleted successfully',
  NOT_FOUND: 'Task not found',
  ACCESS_DENIED: 'Access denied',
  BLOCKED_TASK: 'Task is blocked by incomplete tasks',
  TASK_CREATE_FAILED: 'Failed to create task',
  INVALID_BLOCKED_BY:'invalid blocked id',

  // project messages
  PROJECT_CREATED: 'Project created successfully',
  PROJECT_UPDATED: 'Project updated successfully',
  PROJECT_DELETED: 'Project deleted successfully',  
  CREATE_FAILED: 'Failed to create project',
  MEMBERS_ASSIGNED: 'Members assigned to project successfully',
  ASSIGN_MEMBERS_FAILED: 'Failed to assign members to project',
  TASKS_ASSIGNED: 'Tasks assigned to project successfully',
  ASSIGN_TASKS_FAILED: 'Failed to assign tasks to project',
  FETCH_FAILED: 'Failed to fetch projects',

  DELETE_SUCCESS: 'Deleted successfully',
};